environments:
  default:
    values:
      - ./optionality.yaml
      - ./default-values/values.yaml
  build:
    values:
      - ./default-values/values.yaml
      - ./build-environment/optionality_maximum.yaml
      - ./build-environment/tags_true.yaml
