global:
  hosts:
    ml: "hall922.rnd.gic.ericsson.se"
  registry:
    url: "armdocker.rnd.ericsson.se"
    # Docker registry username
    username: ""
    # Docker registry password
    password: ""
  support:
    ipv6:
      enabled: false
  timezone: UTC
  createClusterRoles: true
  ingressClass: nginx

# Warning! If changing these application tags from true to false and that application
# is already installed, then that application will be removed and data will be lost!
tags:
  ml: true

ml:
  iam:
    username:
    password:
    temporal: false
    kcadminid:
    kcpasswd:
  certs:
    path: "../../certificates"
  config:
    deploymentManager: true
  gitops:
    internal: true
    repoUrl: ""
    branch: "master"
    credentials:
      username:
      password:
      email:
    commit:
      authorName: "MXE Deployer"
      authorEmail: "mxe-deployer@local.domain"
      authorDomain:
  servicecreds:
    minioAdminAccessKey: o6KBywDxDU1bcboqGVP9
    minioAdminSecretKey: 6N2IQNKzJqvNDXyLdHR1ILBilrdrsEzCDEMKhcbG
    pgCustomPassword: JFMtegPhXL
    catalogueServiceInstanceMinioSecretkey: Z7ytrR00VHRN480PT2M3qNLk
    catalogueServiceMinioSecretkey: C2LLYQCbgCcosQkhwHNHSDBB
    trainingjrInstanceMinioSecretkey: i6i2FK4134qqZsntkdij5Wio
    trainingjrServiceMinioSecretkey: 9ybVISOIvUMIEe89tkNJHNkH
    trainingpkgInstanceMinioSecretkey: 5SQ7sqXISkWpOvW3fib2VqXs
    trainingpkgServiceMinioSecretkey: 3kyzuM8DI0hbKvJThaBdxCuV
    catalogueServicePgCustomUserPwd: BGOUtCjJV2ozAn9ps75t97BL
    trainingServicePgCustomUserPwd: CYa5TXnJ6oVhgmt4vh5Gv9Gv
    authorServicePgCustomUserPwd: pI6WGDEO46FplU7aRBum0DFq
    lcmContainerRegistryPassword: eXZgMTTzbU
    argocdAdminPwd: "password"
