{{- if ( and .Values.ml.base ( not .Values.ml.config.deploymentManager )) -}}
{{- with .Values.global.registry }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .pullSecret | quote }}
  labels:
    app.kubernetes.io/part-of: {{ include "eric-oss-ml-execution-env.name" $ | quote }}
    app.kubernetes.io/component: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .pullSecret | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    helm.sh/chart: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  annotations:
    {{- include "eric-oss-ml-execution-env.helm-annotations" $ | nindent 4 }}
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"auth\":\"%s\"}}}" .url .username .password (printf "%s:%s" .username .password | b64enc) | b64enc | quote }}
{{- end }}
{{- end -}}
