{{- if .Values.ml.base -}}
{{- with (index .Values "mxe-commons" "eric-mxe-gatekeeper" "keycloak" "realm" "master" "secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName | quote }}
  labels:
    app.kubernetes.io/part-of: {{ include "eric-oss-ml-execution-env.name" $ | quote }}
    app.kubernetes.io/component: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .secretName | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    helm.sh/chart: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  annotations:
    {{- include "eric-oss-ml-execution-env.helm-annotations" $ | nindent 4 }}
type: Opaque
stringData:
  kcadminid: {{ .kcadminid | quote }}
  kcpasswd: {{ .kcpasswd | quote }}
{{- end }}
---
{{- with (index .Values "mxe-commons" "eric-mxe-gatekeeper" "keycloak" "realm" "mxe" "secret") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .secretName | quote }}
  labels:
    app.kubernetes.io/part-of: {{ include "eric-oss-ml-execution-env.name" $ | quote }}
    app.kubernetes.io/component: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .secretName | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    helm.sh/chart: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  annotations:
    {{- include "eric-oss-ml-execution-env.helm-annotations" $ | nindent 4 }}
type: Opaque
stringData:
  username: {{ .username | quote }}
  password: {{ .password | quote }}
{{- end }}
{{- end -}}
