{{- if .Values.ml.base -}}
{{- if ((.Values.ml).certs).ca }}
{{- $name := index .Values "global" "mxeIamCaSecretName" | quote -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $name }}
  labels:
    app.kubernetes.io/part-of: {{ include "eric-oss-ml-execution-env.name" . | quote }}
    app.kubernetes.io/component: {{ include "eric-oss-ml-execution-env.chart" . | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ $name }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    helm.sh/chart: {{ include "eric-oss-ml-execution-env.chart" . | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  annotations:
    {{- include "eric-oss-ml-execution-env.helm-annotations" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ .Values.ml.certs.ca.crt | b64enc | quote }}
{{- end }}
{{- end -}}
