{{- if .Values.ml.apps -}}
---
apiVersion: v1
kind: Secret
metadata:
  {{- with (index .Values "mxe-deployer" "mxe-deployer-service" "config" "sso" "users") }}
  name: {{ .adminUserSecret | quote }}
  labels:
    app.kubernetes.io/part-of: {{ include "eric-oss-ml-execution-env.name" $ | quote }}
    app.kubernetes.io/component: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion | quote }}
    app.kubernetes.io/name: {{ .adminUserSecret | quote }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
    helm.sh/chart: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/managed-by: {{ $.Release.Service | quote }}
  {{- end }}
  annotations:
    {{- include "eric-oss-ml-execution-env.helm-annotations" $ | nindent 4 }}
type: Opaque
data:
  username: {{ "admin" | b64enc | quote }}
  password: {{ .Values.ml.servicecreds.argocdAdminPwd | b64enc | quote }}
{{- if not (index .Values "mxe-deployer" "argo-cd" "configs" "secret" "createSecret") }}
---
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
  labels:
    app.kubernetes.io/name: argocd-secret
    helm.sh/chart: {{ include "eric-oss-ml-execution-env.chart" $ | quote }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: server
  annotations:
    {{- include "eric-oss-ml-execution-env.helm-annotations" $ | nindent 4 }}
type: Opaque
{{- if .Values.ml.servicecreds.argocdAdminPwd }}
# Setting a blank data again will wipe admin password/key/cert
data:
  admin.password: {{ trimPrefix "admin:" (htpasswd "admin" .Values.ml.servicecreds.argocdAdminPwd) | b64enc }}
  admin.passwordMtime: {{ default (date "2006-01-02T15:04:05Z" now) (index .Values "mxe-deployer" "argo-cd" "configs" "secret" "argocdServerAdminPasswordMtime") | b64enc }}
{{- end }}
{{- end -}}
{{- end -}}
